function cpar = getUndistortPointsNexus5
%     cpar = load('+david/cameraParametersNexus5YUV.mat');
    cpar = load('+david/cameraParametersNexus5MP4.mat');
    Q = vision.internal.calibration.ImageTransformer;
%     Q.update(ones(2448,3264,'single'),cpar.param.IntrinsicMatrix,...
%                                     cpar.param.RadialDistortion,...
%                                     cpar.param.TangentialDistortion,...
%                                     'same',[1 3264],[1 2448]);
    Q.update(ones(1080,1920,'single'),cpar.param.IntrinsicMatrix,...
                                    cpar.param.RadialDistortion,...
                                    cpar.param.TangentialDistortion,...
                                    'same',[1 1920],[1 1080]);
                                
    cpar.Xq = Q.XmapSingle;
    cpar.Yq = Q.YmapSingle;
    clear Q;
end

