function cpar = getUndistortPointsiPhone6sPlus
%     cpar = load('+david/cameraParametersiPhone6sPlus4kMOV.mat');
%     cpar = load('+david/cameraParametersiPhone6sPlus1080MOV.mat');
    cpar = load('cameraParametersGooglePixel1080p120fps.mat');
    Q = vision.internal.calibration.ImageTransformer;
%     Q.update(ones(2160,3840,'single'),cpar.param.IntrinsicMatrix,...
%                                     cpar.param.RadialDistortion,...
%                                     cpar.param.TangentialDistortion,...
%                                     'same',[1 3840],[1 2160]);
    Q.update(ones(1080,1920,'single'),cpar.param.IntrinsicMatrix,...
                                    cpar.param.RadialDistortion,...
                                    cpar.param.TangentialDistortion,...
                                    'same',[1 1920],[1 1080]);
                                
    cpar.Xq = Q.XmapSingle;
    cpar.Yq = Q.YmapSingle;
    clear Q;
end